{% set name = "foyer" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mosdef-hub/foyer/archive/{{ version }}.tar.gz
  sha256: 5a6963fed7ffed8764c2ec1a046f42c84617d96f6a2e22b96d7049ada0e6146e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy
    - ele
    - openmm >=7.6
    - parmed >=3.4.3
    - networkx >=2.5
    - lark-parser
    - requests
    - lxml
    - protobuf
    - python >=3.6
    - gmso >=0.6.0

test:
  imports:
    - foyer

about:
  home: https://github.com/mosdef-hub/foyer
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: Atom-typing and force field dissemination.
  description: |
    Foyer is an open-source Python tool that enables users to define and apply
    force field atom-typing rules in a format that is both human- and
    machine-readable and provides a framework for force field dissemination,
    thus eliminating ambiguity in atom-typing and improving reproducibility.
    Foyer defines force fields in an XML format, where SMARTS strings are used
    to define the chemical context of a particular atom type and "overrides"
    are used to set rule precedence, rather than a rigid hierarchical scheme.
  doc_url: https://foyer.mosdef.org/
  dev_url: https://github.com/mosdef-hub/foyer

extra:
  recipe-maintainers:
    - justinGilmer
    - daico007
    - umesh-timalsina
